import asyncio
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

from app.utils.logger import logger

_EXTENSION_PATTERN = re.compile(r"^[a-z0-9]{1,10}$")


class LocalFileStorage:
    """
    Stores generated files on the local filesystem.

    The development implementation of FileStorage. Keys are date-prefixed
    (`2026/09/04/<uuid>.txt`) for two reasons: a single directory holding
    every file ever generated becomes slow to list and painful to inspect
    by hand, and the same prefix layout maps directly onto S3 object keys,
    so the eventual migration is a copy rather than a rename.
    """

    def __init__(self, root: Path) -> None:
        # Resolved once, so the containment check below compares two
        # absolute paths rather than depending on the working directory.
        self._root = root.resolve()

    def _resolve(self, key: str) -> Path:
        """
        Map a key to a path, refusing anything that escapes the root.

        Keys are generated by this class and stored in our own database, so
        this should never fire. It is here because the cost is one
        comparison and the failure it prevents is arbitrary file access.
        """
        path = (self._root / key).resolve()

        if not path.is_relative_to(self._root):
            raise ValueError(f"Storage key escapes the storage root: {key!r}")

        return path

    async def write(self, data: bytes, *, extension: str) -> str:
        if not _EXTENSION_PATTERN.match(extension):
            raise ValueError(
                f"Extension must be lowercase alphanumeric; got {extension!r}"
            )

        # UTC rather than JST: this prefix is infrastructure, not something
        # a reader sees, and keeping storage independent of the documents
        # package avoids a dependency pointing the wrong way.
        today = datetime.now(tz=timezone.utc).date()

        key = f"{today:%Y/%m/%d}/{uuid.uuid4().hex}.{extension}"
        path = self._resolve(key)

        await asyncio.to_thread(self._write_sync, path, data)

        logger.debug(
            "File written | key=%s bytes=%s",
            key,
            len(data),
        )

        return key

    async def read(self, key: str) -> bytes:
        path = self._resolve(key)

        return await asyncio.to_thread(path.read_bytes)

    async def delete(self, key: str) -> None:
        path = self._resolve(key)

        await asyncio.to_thread(path.unlink, True)

        logger.debug("File deleted | key=%s", key)

    @staticmethod
    def _write_sync(path: Path, data: bytes) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)

        # Write to a temporary name and rename into place. A rename within
        # one filesystem is atomic, so a crash mid-write leaves a stray
        # temp file rather than a truncated document that looks complete.
        temporary = path.with_suffix(path.suffix + ".part")
        temporary.write_bytes(data)
        temporary.replace(path)
